<a href="https://colab.research.google.com/github/pskarthikk/flyrank-ml-internship/blob/main/work/notebooks/w05_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-08 — Capstone Modeling Lane

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Method choice and why

*Which method from the toolkit, and why it fits your lane.*

In [17]:
# Section 1 — Method choice and why

method_choice = """
Method: Logistic Regression, with Random Forest as a stronger comparison model.

Why it fits this lane:
The lane asks which content pages should be prioritized for review, so the model
needs to produce a probability score that can rank pages rather than only a hard
yes/no prediction. The target is the observed declining-page label.

Logistic Regression is the first model because it is relatively simple and
interpretable for a binary outcome. Random Forest is included as a stronger
non-linear comparison to test whether additional model complexity improves the
ranking.

Both models will use the same official feature set and the same client-holdout
test set. The primary ranking metrics will be Precision@20, Precision@50, and
Precision@100. The Week-4 rule baseline will be evaluated on the same held-out
rows and included in the final comparison.
"""

print(method_choice)


Method: Logistic Regression, with Random Forest as a stronger comparison model.

Why it fits this lane:
The lane asks which content pages should be prioritized for review, so the model
needs to produce a probability score that can rank pages rather than only a hard
yes/no prediction. The target is the observed declining-page label.

Logistic Regression is the first model because it is relatively simple and
interpretable for a binary outcome. Random Forest is included as a stronger
non-linear comparison to test whether additional model complexity improves the
ranking.

Both models will use the same official feature set and the same client-holdout
test set. The primary ranking metrics will be Precision@20, Precision@50, and
Precision@100. The Week-4 rule baseline will be evaluated on the same held-out
rows and included in the final comparison.



In [3]:
from pathlib import Path

skills_dir = Path("/content/flyrank-ml-internship/skills")

print("README exists:", (skills_dir / "README.md").exists())

if (skills_dir / "README.md").exists():
    print("\n--- skills/README.md ---\n")
    print((skills_dir / "README.md").read_text())

README exists: False


In [4]:
from pathlib import Path

matches = []

for base in [Path("/content"), Path("/mnt/data"), Path("/home/oai")]:
    if base.exists():
        for p in base.rglob("flyrank-ml-internship"):
            if p.is_dir():
                matches.append(str(p))

print("Found repositories:")
for m in matches:
    print(m)

Found repositories:


In [5]:
import subprocess

result = subprocess.run(
    ["git", "--version"],
    capture_output=True,
    text=True
)

print(result.stdout.strip())

git version 2.34.1


In [6]:
import subprocess
from pathlib import Path

repo_url = "https://github.com/pskarthikk/flyrank-ml-internship.git"
repo_path = Path("/content/flyrank-ml-internship")

if repo_path.exists():
    print("Repository already exists:", repo_path)
else:
    result = subprocess.run(
        ["git", "clone", repo_url, str(repo_path)],
        capture_output=True,
        text=True
    )

    print(result.stdout)
    if result.stderr:
        print(result.stderr)

print("\nRepo exists:", repo_path.exists())


Cloning into '/content/flyrank-ml-internship'...


Repo exists: True


In [7]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")
skills_dir = repo / "skills"

print("Skills directory exists:", skills_dir.exists())
print("\nAvailable skill files:")

for p in sorted(skills_dir.rglob("*")):
    if p.is_file():
        print(p.relative_to(repo))

Skills directory exists: True

Available skill files:
skills/README.md
skills/auditing-signals/SKILL.md
skills/building-baselines/SKILL.md
skills/deploying-static-pages/SKILL.md
skills/directing-your-ai-assistant/SKILL.md
skills/flyrank/flyrank-context/SKILL.md
skills/flyrank/flyrank-data/SKILL.md
skills/framing-ml-problems/SKILL.md
skills/hunting-leakage-and-validating/SKILL.md
skills/querying-big-datasets/SKILL.md
skills/training-honest-models/SKILL.md
skills/writing-data-contracts/SKILL.md
skills/writing-honest-claims/SKILL.md
skills/writing-research-papers/SKILL.md


In [8]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")

files = [
    repo / "skills" / "README.md",
    repo / "skills" / "training-honest-models" / "SKILL.md",
    repo / "skills" / "flyrank" / "flyrank-data" / "SKILL.md",
]

for file in files:
    print("\n" + "=" * 80)
    print(f"FILE: {file.relative_to(repo)}")
    print("=" * 80)
    print(file.read_text())


FILE: skills/README.md
# Skills — the router

This folder is a small library of **skills**: focused instruction files your AI assistant loads
one at a time. One skill per task keeps the assistant sharp — its context window is small, and
filling it with everything makes it worse at the one thing you need.

**How to use it (repo-reading agents — Claude Code, Cursor, Codex):** they find this file
automatically via `AGENTS.md` / `CLAUDE.md`. Just tell your assistant which task you're doing.

**Using a chat-only assistant (ChatGPT / Gemini in a browser)?** Open the skill file on GitHub,
copy its whole content, and paste it into your chat before asking for help. That's it.

## The table — find your task, load ONE skill

| Your task | Load this skill | Also load for data work |
|---|---|---|
| Any task — how to work with your assistant at all | `directing-your-ai-assistant/SKILL.md` | — |
| Pick a lane, frame your question (ML-02, ML-03) | `framing-ml-problems/SKILL.md` | `flyrank/flyrank-da

In [9]:
from pathlib import Path
import json

repo = Path("/content/flyrank-ml-internship")
notebook = repo / "work/notebooks/w04_baseline_score.ipynb"

print("Notebook exists:", notebook.exists())

nb = json.loads(notebook.read_text())

for i, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "code":
        source = "".join(cell["source"])
        print("\n" + "=" * 80)
        print(f"CODE CELL {i}")
        print("=" * 80)
        print(source)

Notebook exists: True

CODE CELL 4
!git clone https://github.com/pskarthikk/flyrank-ml-internship.git
%cd flyrank-ml-internship

!ls

CODE CELL 5
# Inspect the available files and folders needed for ML-07
from pathlib import Path

print("Current directory:", Path.cwd())
print("\nwork/notebooks exists:", Path("work/notebooks").exists())
print("data/processed exists:", Path("data/processed").exists())
print("data/raw exists:", Path("data/raw").exists())

if Path("data/processed").exists():
    print("\nProcessed files:")
    for p in Path("data/processed").iterdir():
        print(" -", p)

if Path("data/raw").exists():
    print("\nRaw files:")
    for p in Path("data/raw").iterdir():
        print(" -", p)

CODE CELL 6
from pathlib import Path

print("Available skills:")
for p in Path("skills").rglob("README.md"):
    print(p)

print("\nSkill directories:")
for p in Path("skills").iterdir():
    print("-", p)

CODE CELL 7
from pathlib import Path

files = [
    Path("skills/building-ba

In [10]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")
dictionary = repo / "docs/data-dictionary.md"

print("Data dictionary exists:", dictionary.exists())

print("\n" + "=" * 80)
print("DATA DICTIONARY")
print("=" * 80)

print(dictionary.read_text())

Data dictionary exists: True

DATA DICTIONARY
# Data Dictionary — `content_refresh_anonymized.csv`

One row per content item (page): **30,000 rows × 44 columns**, covering **32 pseudonymized
clients**. All metrics are aggregated over a trailing 90-day window ending at export time.
Keep this file open while you work.

## Read this first — the three rules that prevent 90% of mistakes

1. **Rate columns are ×100 percentages.** `ctr = 0.76` means **0.76%**, not 76%. Applies to
   `ctr`, `engagement_rate`, `scroll_rate`, `ai_traffic_pct`, `trend_pct`.
2. **The label comes from `trend_direction`.** The pipeline defines
   `is_declining_label = (trend_direction == "down")`, so `trend_direction` and `trend_pct`
   must **never** be model features — that's the leakage notebook 02 demonstrates.
3. **IDs are for grouping only.** `content_id` / `client_id` are pseudonyms: use them for
   joins and grouped train/test splits, never as features.

## Identifiers

| Column | Type | Meaning | Notes |
|-

In [11]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")
ml_utils = repo / "scripts/ml_utils.py"

print("File exists:", ml_utils.exists())

print("\n" + "=" * 80)
print("scripts/ml_utils.py")
print("=" * 80)

print(ml_utils.read_text())

File exists: True

scripts/ml_utils.py
from __future__ import annotations

import json
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
RAW_PATH = ROOT / "data" / "raw" / "content_refresh_anonymized.csv"
PROCESSED_DIR = ROOT / "data" / "processed"
OUTPUT_DIR = ROOT / "outputs"
CHART_DIR = OUTPUT_DIR / "charts"


NUMERIC_COLUMNS = [
    "search_volume",
    "competition",
    "cpc",
    "word_count",
    "char_count",
    "impressions_90d",
    "clicks_90d",
    "pageviews_90d",
    "sessions_90d",
    "users_90d",
    "engaged_sessions_90d",
    "ai_sessions_90d",
    "scroll_events_90d",
    "days_with_impressions",
    "days_with_sessions",
    "impressions_last_30d",
    "clicks_last_30d",
    "sessions_last_30d",
    "impressions_prev_30d",
    "clicks_prev_30d",
    "sessions_prev_30d",
    "content_age_days",
    "age_tier_order",
    "days_since_last_update",
    "ctr",
    "avg_position",
 

In [12]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")

keywords = [
    "GroupShuffleSplit",
    "GroupKFold",
    "train_test_split",
    "LogisticRegression",
    "RandomForestClassifier",
    "MODEL_NUMERIC_FEATURES",
    "MODEL_CATEGORICAL_FEATURES",
]

for keyword in keywords:
    print("\n" + "=" * 80)
    print("SEARCH:", keyword)
    print("=" * 80)

    found = False

    for path in repo.rglob("*"):
        if path.is_file() and ".git" not in path.parts:
            try:
                text = path.read_text(errors="ignore")
            except Exception:
                continue

            if keyword in text:
                found = True
                print(path.relative_to(repo))

    if not found:
        print("No matches")


SEARCH: GroupShuffleSplit
notebooks/03_working_with_the_full_release.ipynb

SEARCH: GroupKFold
skills/hunting-leakage-and-validating/SKILL.md

SEARCH: train_test_split
notebooks/03_working_with_the_full_release.ipynb
scripts/03_train_model.py

SEARCH: LogisticRegression
scripts/03_train_model.py

SEARCH: RandomForestClassifier
notebooks/03_working_with_the_full_release.ipynb
scripts/03_train_model.py

SEARCH: MODEL_NUMERIC_FEATURES
GUIDE.md
docs/data-dictionary.md
scripts/ml_utils.py
scripts/01_prepare_features.py
scripts/03_train_model.py

SEARCH: MODEL_CATEGORICAL_FEATURES
GUIDE.md
docs/data-dictionary.md
scripts/ml_utils.py
scripts/01_prepare_features.py
scripts/03_train_model.py


In [13]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")

files = [
    repo / "scripts/03_train_model.py",
    repo / "skills/hunting-leakage-and-validating/SKILL.md",
]

for file in files:
    print("\n" + "=" * 100)
    print(f"FILE: {file.relative_to(repo)}")
    print("=" * 100)
    print(file.read_text())


FILE: scripts/03_train_model.py
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

from ml_utils import (
    MODEL_CATEGORICAL_FEATURES,
    MODEL_NUMERIC_FEATURES,
    OUTPUT_DIR,
    PROCESSED_DIR,
    display_path,
    precision_at_k,
    write_json,
)


FEATURE_PATH = PROCESSED_DIR / "refresh_feature_vector.csv"
BASELINE_PATH = PROCESSED_DIR / "baseline_refresh_queue.csv"
PREDICTION_PATH = PROCESSED_DIR / "model_predictions.csv"
RESULT_PATH = OUTPUT_DIR / "model_results.json"
R

In [14]:
from pathlib import Path

repo = Path("/content/flyrank-ml-internship")

paths = [
    repo / "data/raw/content_refresh_anonymized.csv",
    repo / "data/processed/refresh_feature_vector.csv",
    repo / "data/processed/baseline_refresh_queue.csv",
    repo / "work/outputs/baseline_action_score.csv",
]

for path in paths:
    print(f"{path.relative_to(repo)}")
    print(f"  Exists: {path.exists()}")
    if path.exists():
        print(f"  Size: {path.stat().st_size:,} bytes")
    print()

data/raw/content_refresh_anonymized.csv
  Exists: True
  Size: 6,727,670 bytes

data/processed/refresh_feature_vector.csv
  Exists: False

data/processed/baseline_refresh_queue.csv
  Exists: False

work/outputs/baseline_action_score.csv
  Exists: False



In [15]:
from pathlib import Path
import sys

repo = Path("/content/flyrank-ml-internship")

# Make the repository scripts importable.
sys.path.insert(0, str(repo / "scripts"))

from ml_utils import (
    MODEL_NUMERIC_FEATURES,
    MODEL_CATEGORICAL_FEATURES,
)

import numpy as np
import pandas as pd

RAW_PATH = repo / "data/raw/content_refresh_anonymized.csv"
FEATURE_PATH = repo / "data/processed/refresh_feature_vector.csv"

# Load raw data
df = pd.read_csv(RAW_PATH)

# Create the target.
# This is the outcome we want to predict, not a model feature.
df["is_declining_label"] = (
    df["trend_direction"] == "down"
).astype(int)

# Create the log features required by ml_utils.py.
for source, target in [
    ("impressions_90d", "log_impressions_90d"),
    ("clicks_90d", "log_clicks_90d"),
    ("sessions_90d", "log_sessions_90d"),
    ("ai_sessions_90d", "log_ai_sessions_90d"),
]:
    values = pd.to_numeric(df[source], errors="coerce").fillna(0)
    df[target] = np.log1p(values)

# Verify all official model features exist.
required_features = (
    MODEL_NUMERIC_FEATURES
    + MODEL_CATEGORICAL_FEATURES
)

missing_features = [
    col for col in required_features
    if col not in df.columns
]

print("Rows:", len(df))
print("Target positive rows:", int(df["is_declining_label"].sum()))
print("Target positive rate:", round(df["is_declining_label"].mean(), 4))
print("Missing official model features:", missing_features)

assert not missing_features

# Keep the fields needed for modeling and grouped validation.
keep_columns = [
    "content_id",
    "client_id",
    "is_declining_label",
] + required_features

feature_df = df[keep_columns].copy()

# Save the prepared feature vector.
FEATURE_PATH.parent.mkdir(parents=True, exist_ok=True)
feature_df.to_csv(FEATURE_PATH, index=False)

print("\nFeature vector written to:")
print(FEATURE_PATH)

print("\nFeature vector shape:", feature_df.shape)
print("Numeric features:", len(MODEL_NUMERIC_FEATURES))
print("Categorical features:", len(MODEL_CATEGORICAL_FEATURES))

Rows: 30000
Target positive rows: 16262
Target positive rate: 0.5421
Missing official model features: []

Feature vector written to:
/content/flyrank-ml-internship/data/processed/refresh_feature_vector.csv

Feature vector shape: (30000, 29)
Numeric features: 18
Categorical features: 8


In [16]:
import numpy as np
import pandas as pd

# Load the prepared feature vector.
feature_df = pd.read_csv(
    "/content/flyrank-ml-internship/data/processed/refresh_feature_vector.csv"
)

RANDOM_STATE = 42

# Keep client_id for grouping, but never use it as a model feature.
client_series = feature_df["client_id"].fillna("unknown").astype(str)

unique_clients = client_series.drop_duplicates().to_numpy()

rng = np.random.default_rng(RANDOM_STATE)
shuffled_clients = rng.permutation(unique_clients)

test_client_count = max(
    1,
    int(round(len(shuffled_clients) * 0.20))
)

test_clients = set(shuffled_clients[:test_client_count])

test_mask = client_series.isin(test_clients)

train_indices = np.flatnonzero(~test_mask.to_numpy())
test_indices = np.flatnonzero(test_mask.to_numpy())

y = feature_df["is_declining_label"].astype(int)

print("Total clients:", len(unique_clients))
print("Held-out clients:", len(test_clients))
print("Training clients:", len(unique_clients) - len(test_clients))

print("\nTrain rows:", len(train_indices))
print("Test rows:", len(test_indices))

print("\nTrain declining rate:", round(y.iloc[train_indices].mean(), 4))
print("Test declining rate:", round(y.iloc[test_indices].mean(), 4))

print("\nTrain classes:", sorted(y.iloc[train_indices].unique().tolist()))
print("Test classes:", sorted(y.iloc[test_indices].unique().tolist()))

print("\nHeld-out client IDs:")
print(sorted(test_clients))

assert len(train_indices) > 0
assert len(test_indices) > 0
assert y.iloc[train_indices].nunique() == 2
assert y.iloc[test_indices].nunique() == 2

print("\nClient-holdout validation: PASS")

Total clients: 32
Held-out clients: 6
Training clients: 26

Train rows: 27675
Test rows: 2325

Train declining rate: 0.5548
Test declining rate: 0.391

Train classes: [0, 1]
Test classes: [0, 1]

Held-out client IDs:
['client_0b918943df', 'client_1a6562590e', 'client_4fc82b26ae', 'client_98a3ab7c34', 'client_d4735e3a26', 'client_f74efabef1']

Client-holdout validation: PASS


## 2. Split design

*Grouped by client? Time-aware? Say why this split is honest for your question.*

### Split design

I use a **client-holdout split** so that pages from the same client do not appear in both training and test data. This tests whether the model can generalize to clients it did not see during training.

The split uses a fixed random seed of 42 and holds out 20% of the 32 clients. This produces 27,675 training rows and 2,325 test rows. Both subsets contain both target classes.

The Week-4 baseline and all learned models will be evaluated on these same 2,325 held-out rows.

In [18]:
# Section 2 — Split design

print("Validation design: client holdout")
print("Random seed: 42")
print("Total clients:", len(unique_clients))
print("Training clients:", len(unique_clients) - len(test_clients))
print("Held-out clients:", len(test_clients))
print("Training rows:", len(train_indices))
print("Test rows:", len(test_indices))
print("Training declining rate:", round(y.iloc[train_indices].mean(), 4))
print("Test declining rate:", round(y.iloc[test_indices].mean(), 4))

assert len(train_indices) == 27675
assert len(test_indices) == 2325
assert y.iloc[train_indices].nunique() == 2
assert y.iloc[test_indices].nunique() == 2

print("\nSplit validation: PASS")
print("Client IDs are retained only for grouping and are not model features.")

Validation design: client holdout
Random seed: 42
Total clients: 32
Training clients: 26
Held-out clients: 6
Training rows: 27675
Test rows: 2325
Training declining rate: 0.5548
Test declining rate: 0.391

Split validation: PASS
Client IDs are retained only for grouping and are not model features.


## 3. Train + compare vs my baseline

*Same data, same metric, same split as your Week-4 baseline. Show the table.*

## 4. Errors and interpretation

*Where is the model wrong? What does it lean on? A short error analysis beats a big metric table.*

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.